/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dingr
 */
public class AddEmployee extends javax.swing.JFrame {

    // ATTRIBUTES
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.
    private int empGender;
    private int workLoc;
    private int empType;
    
    //METHODS
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
    
     // CONSTRUCTORS
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        partTimeEmpPanel.setVisible(false);
        fullTimeEmpPanel.setVisible(false);
        empAdded.setVisible(false);
        error.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        workLocButtonGroup = new javax.swing.ButtonGroup();
        empTypeButtonGroup = new javax.swing.ButtonGroup();
        empNum = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        deductRate = new javax.swing.JTextField();
        partTimeEmpPanel = new javax.swing.JPanel();
        hourWage = new javax.swing.JTextField();
        hourPerWeek = new javax.swing.JTextField();
        weekPerYear = new javax.swing.JTextField();
        hourWageLabel = new java.awt.Label();
        hourPerWeekLabel = new java.awt.Label();
        weekPerYearLabel = new java.awt.Label();
        fullTimeEmpPanel = new javax.swing.JPanel();
        yearSalary = new javax.swing.JTextField();
        yearSalaryLabel = new java.awt.Label();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        otherGender = new javax.swing.JRadioButton();
        workLocMississauga = new javax.swing.JRadioButton();
        workLocBrampton = new javax.swing.JRadioButton();
        workLocOakville = new javax.swing.JRadioButton();
        FTE = new javax.swing.JRadioButton();
        PTE = new javax.swing.JRadioButton();
        empNumLabel = new java.awt.Label();
        genderLabel = new java.awt.Label();
        firstNameLabel = new java.awt.Label();
        lastNameLabel = new java.awt.Label();
        deductRateLabel = new java.awt.Label();
        workLocLabel = new java.awt.Label();
        percentSign = new java.awt.Label();
        empTypeLabel = new java.awt.Label();
        addToTable = new javax.swing.JButton();
        dispose = new javax.swing.JButton();
        empAdded = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        partTimeEmpPanel.setBackground(new java.awt.Color(255, 255, 255));

        hourWageLabel.setText("Hourly Wage:");

        hourPerWeekLabel.setText("Hours Per Week:");

        weekPerYearLabel.setText("Weeks Per Year:");

        javax.swing.GroupLayout partTimeEmpPanelLayout = new javax.swing.GroupLayout(partTimeEmpPanel);
        partTimeEmpPanel.setLayout(partTimeEmpPanelLayout);
        partTimeEmpPanelLayout.setHorizontalGroup(
            partTimeEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partTimeEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourWage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        partTimeEmpPanelLayout.setVerticalGroup(
            partTimeEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hourWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(weekPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        fullTimeEmpPanel.setBackground(new java.awt.Color(255, 255, 255));

        yearSalaryLabel.setText("Yearly Salary:");

        javax.swing.GroupLayout fullTimeEmpPanelLayout = new javax.swing.GroupLayout(fullTimeEmpPanel);
        fullTimeEmpPanel.setLayout(fullTimeEmpPanelLayout);
        fullTimeEmpPanelLayout.setHorizontalGroup(
            fullTimeEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fullTimeEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        fullTimeEmpPanelLayout.setVerticalGroup(
            fullTimeEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        genderButtonGroup.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        genderButtonGroup.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        genderButtonGroup.add(otherGender);
        otherGender.setText("Other");
        otherGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherGenderActionPerformed(evt);
            }
        });

        workLocButtonGroup.add(workLocMississauga);
        workLocMississauga.setText("Mississauga");
        workLocMississauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocMississaugaActionPerformed(evt);
            }
        });

        workLocButtonGroup.add(workLocBrampton);
        workLocBrampton.setText("Brampton");
        workLocBrampton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocBramptonActionPerformed(evt);
            }
        });

        workLocButtonGroup.add(workLocOakville);
        workLocOakville.setText("Oakville");
        workLocOakville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocOakvilleActionPerformed(evt);
            }
        });

        empTypeButtonGroup.add(FTE);
        FTE.setText("Full Time Employee");
        FTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTEActionPerformed(evt);
            }
        });

        empTypeButtonGroup.add(PTE);
        PTE.setText("Part Time Employee");
        PTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTEActionPerformed(evt);
            }
        });

        empNumLabel.setText("Employee Number:");

        genderLabel.setText("Gender:");

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        deductRateLabel.setText("Deduction Rate:");

        workLocLabel.setText("Work Location:");

        percentSign.setText("%");

        empTypeLabel.setText("Employee Type:");

        addToTable.setText("Add To Hashtable");
        addToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToTableActionPerformed(evt);
            }
        });

        dispose.setText("Cancel");
        dispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposeActionPerformed(evt);
            }
        });

        empAdded.setText("Item successfully added");

        error.setText("Duplicate emp# or null fields");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(male)
                                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(otherGender)
                                    .addComponent(female))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(workLocBrampton)
                                    .addComponent(workLocMississauga)
                                    .addComponent(workLocOakville))
                                .addGap(10, 10, 10)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FTE)
                            .addComponent(PTE)
                            .addComponent(empTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empAdded)
                            .addComponent(deductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(percentSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(error)
                                    .addComponent(addToTable)
                                    .addComponent(dispose))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullTimeEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partTimeEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(workLocMississauga)
                    .addComponent(FTE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(female)
                    .addComponent(workLocBrampton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(PTE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherGender)
                    .addComponent(workLocOakville))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addToTable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dispose)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(error))
                            .addComponent(fullTimeEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empAdded))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(partTimeEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToTableActionPerformed
        // TODO add your handling code here:
        //Adds Employee to hashtable
        FTE theFTE;
        PTE thePTE;
        
        //Input for employee-number of added employee
        if ("".equals(empNum.getText()) || "".equals(firstName.getText()) || "".equals(lastName.getText()) || "".equals(deductRate.getText())) { //Detects for empty text fields
            System.out.println("empty fields");
            error.setVisible(true);
        } else {
            error.setVisible(false);
            
            //Input for empNum
            String employeeNumString = empNum.getText();
            int employeeNum = Integer.parseInt(employeeNumString);
            EmployeeInfo isInTable = mainHT.searchFromTable(employeeNum);
            
            //Input for first and last names
            String employeeFirst = firstName.getText();
            String employeeLast = lastName.getText();

            //Input for deduction rate
            String employeeDeductString = deductRate.getText();
            double employeeDeduct = Double.parseDouble(employeeDeductString) / 100;

            if (empType == 0) {//Adds FTE 

                if ("".equals(yearSalary.getText()) || isInTable != null) {//Detects FTE empty fields and detects duplicate emp#
                    System.out.println("empty fields or emp# already exists");
                    error.setVisible(true);
                    empAdded.setVisible(false);
                } else {
                    error.setVisible(false);
                    String employeeYearSalaryString = yearSalary.getText();
                    double employeeYearSalary = Double.parseDouble(employeeYearSalaryString);

                    theFTE = new FTE(employeeNum, employeeFirst, employeeLast, empGender, workLoc, employeeDeduct, employeeYearSalary);
                    mainHT.addToTable(theFTE);
                    System.out.println("Added the FTE to the hash table!");
                    empAdded.setVisible(true);
                }
            }

            if (empType == 1) {//Adds PTE 

                if ("".equals(hourWage.getText()) || "".equals(hourPerWeek.getText()) || "".equals(weekPerYear.getText()) || isInTable != null) {//Detects PTE empty fields and detects duplicate emp#
                    System.out.println("empty fields or emp# already exists");
                    error.setVisible(true);
                    empAdded.setVisible(false);
                } else {
                    error.setVisible(false);
                    String employeeHourWageString = hourWage.getText();
                    double employeeHourWage = Double.parseDouble(employeeHourWageString);

                    String employeeHourPerWeekString = hourPerWeek.getText();
                    double employeeHourPerWeek = Double.parseDouble(employeeHourPerWeekString);

                    String employeeWeekPerYearString = weekPerYear.getText();
                    double employeeWeekPerYear = Double.parseDouble(employeeWeekPerYearString);

                    thePTE = new PTE(employeeNum, employeeFirst, employeeLast, empGender, workLoc, employeeDeduct, employeeHourWage, employeeHourPerWeek, employeeWeekPerYear);
                    mainHT.addToTable(thePTE);
                    System.out.println("Added the PTE to the hash table!");
                    empAdded.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_addToTableActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        //Sets gender to female, which is 2
        empGender = 2;
    }//GEN-LAST:event_femaleActionPerformed

    private void otherGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherGenderActionPerformed
        // TODO add your handling code here:
        //Sets gender to other, which is 0
        empGender = 0;
    }//GEN-LAST:event_otherGenderActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        //Sets gender to male, which is 1
        empGender = 1;
    }//GEN-LAST:event_maleActionPerformed

    private void disposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposeActionPerformed
        // TODO add your handling code here:
        //Closes AddEmployee Tab
        dispose();
    }//GEN-LAST:event_disposeActionPerformed

    private void workLocOakvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocOakvilleActionPerformed
        // TODO add your handling code here:
        //Sets work location to Oakville, which is 2
        workLoc = 2;
    }//GEN-LAST:event_workLocOakvilleActionPerformed

    private void workLocBramptonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocBramptonActionPerformed
        // TODO add your handling code here:
        //Sets work location to Brampton, which is 1
        workLoc = 1;
    }//GEN-LAST:event_workLocBramptonActionPerformed

    private void workLocMississaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocMississaugaActionPerformed
        // TODO add your handling code here:
        //Sets work location to Mississauga, which is 0
        workLoc = 0;
    }//GEN-LAST:event_workLocMississaugaActionPerformed

    private void PTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTEActionPerformed
        // TODO add your handling code here:
        //Sets PTE panel visible
        partTimeEmpPanel.setVisible(true);
        fullTimeEmpPanel.setVisible(false);
        empType = 1;
    }//GEN-LAST:event_PTEActionPerformed

    private void FTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTEActionPerformed
        // TODO add your handling code here:
        //Sets FTE panel visible
        partTimeEmpPanel.setVisible(false);
        fullTimeEmpPanel.setVisible(true);
        empType = 0;
    }//GEN-LAST:event_FTEActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //Save HashTable to archive file after close
        mainHT.saveToFile("D:\\Dump\\CompSci\\HTarchive.txt");
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FTE;
    private javax.swing.JRadioButton PTE;
    private javax.swing.JButton addToTable;
    private javax.swing.JTextField deductRate;
    private java.awt.Label deductRateLabel;
    private javax.swing.JButton dispose;
    private javax.swing.JLabel empAdded;
    private javax.swing.JTextField empNum;
    private java.awt.Label empNumLabel;
    private javax.swing.ButtonGroup empTypeButtonGroup;
    private java.awt.Label empTypeLabel;
    private javax.swing.JLabel error;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstName;
    private java.awt.Label firstNameLabel;
    private javax.swing.JPanel fullTimeEmpPanel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private java.awt.Label genderLabel;
    private javax.swing.JTextField hourPerWeek;
    private java.awt.Label hourPerWeekLabel;
    private javax.swing.JTextField hourWage;
    private java.awt.Label hourWageLabel;
    private javax.swing.JTextField lastName;
    private java.awt.Label lastNameLabel;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton otherGender;
    private javax.swing.JPanel partTimeEmpPanel;
    private java.awt.Label percentSign;
    private javax.swing.JTextField weekPerYear;
    private java.awt.Label weekPerYearLabel;
    private javax.swing.JRadioButton workLocBrampton;
    private javax.swing.ButtonGroup workLocButtonGroup;
    private java.awt.Label workLocLabel;
    private javax.swing.JRadioButton workLocMississauga;
    private javax.swing.JRadioButton workLocOakville;
    private javax.swing.JTextField yearSalary;
    private java.awt.Label yearSalaryLabel;
    // End of variables declaration//GEN-END:variables
}
