/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dingr
 */
public class EditEmployee extends javax.swing.JFrame {

    // ATTRIBUTES
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.
    private PTE empEditedPTE; 
    private FTE empEditedFTE; 
    private EmployeeInfo empEdited; 
    private int empGender;
    private int workLoc;
    private int empType;
    
    // METHODS
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
    
    // CONSTRUCTORS
    /**
     * Creates new form RemoveEmployee
     */
    public EditEmployee() {
        initComponents();
        errorLabel.setVisible(false);
        nullLabel.setVisible(false);
        PTEPanel.setVisible(false);
        FTEPanel.setVisible(false);
        empEditedLabel.setVisible(false);
        editEmpPanel.setVisible(false);
        error.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        workLocButtonGroup = new javax.swing.ButtonGroup();
        empTypeButtonGroup = new javax.swing.ButtonGroup();
        empFind = new javax.swing.JTextField();
        findEmp = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        empNumLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        nullLabel = new javax.swing.JLabel();
        editEmpPanel = new javax.swing.JPanel();
        empNum = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        deductRate = new javax.swing.JTextField();
        PTEPanel = new javax.swing.JPanel();
        hourWage = new javax.swing.JTextField();
        hourPerWeek = new javax.swing.JTextField();
        weekPerYear = new javax.swing.JTextField();
        hourWageLabel = new java.awt.Label();
        hourPerWeekLabel = new java.awt.Label();
        weekPerYearLabel = new java.awt.Label();
        FTEPanel = new javax.swing.JPanel();
        yearSalary = new javax.swing.JTextField();
        yearSalaryLabel = new java.awt.Label();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        otherGender = new javax.swing.JRadioButton();
        workLocMississauga = new javax.swing.JRadioButton();
        workLocBrampton = new javax.swing.JRadioButton();
        workLocOakville = new javax.swing.JRadioButton();
        FTE = new javax.swing.JRadioButton();
        PTE = new javax.swing.JRadioButton();
        empNumLabel1 = new java.awt.Label();
        firstNameLabel = new java.awt.Label();
        lastNameLabel = new java.awt.Label();
        deductRateLabel = new java.awt.Label();
        workLocLabel = new java.awt.Label();
        percentLabel = new java.awt.Label();
        genderLabel = new java.awt.Label();
        empTypeLabel = new java.awt.Label();
        addToTable = new javax.swing.JButton();
        dispose = new javax.swing.JButton();
        empEditedLabel = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        findEmp.setText("Find...");
        findEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findEmpActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        empNumLabel.setText("Employee Number:");

        errorLabel.setText("Error: Could not find employee");

        nullLabel.setText("Please add an employee number");

        PTEPanel.setBackground(new java.awt.Color(255, 255, 255));

        hourWageLabel.setText("Hourly Wage:");

        hourPerWeekLabel.setText("Hours Per Week:");

        weekPerYearLabel.setText("Weeks Per Year:");

        javax.swing.GroupLayout PTEPanelLayout = new javax.swing.GroupLayout(PTEPanel);
        PTEPanel.setLayout(PTEPanelLayout);
        PTEPanelLayout.setHorizontalGroup(
            PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourWage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PTEPanelLayout.setVerticalGroup(
            PTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hourWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(weekPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        FTEPanel.setBackground(new java.awt.Color(255, 255, 255));

        yearSalaryLabel.setText("Yearly Salary:");

        javax.swing.GroupLayout FTEPanelLayout = new javax.swing.GroupLayout(FTEPanel);
        FTEPanel.setLayout(FTEPanelLayout);
        FTEPanelLayout.setHorizontalGroup(
            FTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        FTEPanelLayout.setVerticalGroup(
            FTEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FTEPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yearSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        genderButtonGroup.add(male);
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        genderButtonGroup.add(female);
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        genderButtonGroup.add(otherGender);
        otherGender.setText("Other");
        otherGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherGenderActionPerformed(evt);
            }
        });

        workLocButtonGroup.add(workLocMississauga);
        workLocMississauga.setText("Mississauga");
        workLocMississauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocMississaugaActionPerformed(evt);
            }
        });

        workLocButtonGroup.add(workLocBrampton);
        workLocBrampton.setText("Brampton");
        workLocBrampton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocBramptonActionPerformed(evt);
            }
        });

        workLocButtonGroup.add(workLocOakville);
        workLocOakville.setText("Oakville");
        workLocOakville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocOakvilleActionPerformed(evt);
            }
        });

        empTypeButtonGroup.add(FTE);
        FTE.setText("Full Time Employee");
        FTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTEActionPerformed(evt);
            }
        });

        empTypeButtonGroup.add(PTE);
        PTE.setText("Part Time Employee");
        PTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTEActionPerformed(evt);
            }
        });

        empNumLabel1.setText("Employee Number:");

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        deductRateLabel.setText("Deduction Rate:");

        workLocLabel.setText("Work Location:");

        percentLabel.setText("%");

        genderLabel.setText("Gender:");

        empTypeLabel.setText("Employee Type:");

        addToTable.setText("Edit Info");
        addToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToTableActionPerformed(evt);
            }
        });

        dispose.setText("Cancel");
        dispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disposeActionPerformed(evt);
            }
        });

        empEditedLabel.setText("Item successfully edited");

        error.setText("Duplicate emp# or null fields");

        javax.swing.GroupLayout editEmpPanelLayout = new javax.swing.GroupLayout(editEmpPanel);
        editEmpPanel.setLayout(editEmpPanelLayout);
        editEmpPanelLayout.setHorizontalGroup(
            editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editEmpPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editEmpPanelLayout.createSequentialGroup()
                        .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editEmpPanelLayout.createSequentialGroup()
                        .addComponent(deductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(editEmpPanelLayout.createSequentialGroup()
                            .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(otherGender)
                                .addComponent(female)
                                .addComponent(male)
                                .addGroup(editEmpPanelLayout.createSequentialGroup()
                                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(workLocMississauga)
                                        .addComponent(workLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(workLocBrampton)
                                        .addComponent(workLocOakville)
                                        .addComponent(FTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(addToTable)
                                .addComponent(dispose)
                                .addComponent(empEditedLabel)
                                .addComponent(error))
                            .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editEmpPanelLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(empTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(editEmpPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(PTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(17, 17, 17))
                        .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FTE)
                            .addComponent(PTE)))))
        );
        editEmpPanelLayout.setVerticalGroup(
            editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workLocLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(workLocMississauga)
                    .addComponent(FTE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(female)
                    .addComponent(workLocBrampton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(PTE))
                .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editEmpPanelLayout.createSequentialGroup()
                        .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherGender)
                            .addComponent(workLocOakville))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(addToTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dispose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empEditedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error)
                        .addGap(21, 21, 21))
                    .addGroup(editEmpPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PTEPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNumLabel)
                            .addComponent(empFind, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(findEmp)
                        .addGap(18, 18, 18)
                        .addComponent(cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabel)
                            .addComponent(nullLabel)
                            .addComponent(editEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nullLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findEmp)
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findEmpActionPerformed
        // TODO add your handling code here:
        //Fills textfields and edits existing employee-If employee type changes, deletes current emp and adds new...updated emp
        if (empFind.getText().equals("")) {
            System.out.println("No employee number added");
            nullLabel.setVisible(true);
            errorLabel.setVisible(false);
            editEmpPanel.setVisible(false);
        } else {

            nullLabel.setVisible(false);
            errorLabel.setVisible(false);

            int empFindInt = Integer.parseInt(empFind.getText());
            empEdited = mainHT.searchFromTable(empFindInt);

            if (empEdited != null) {

                System.out.println("Employee found");
                editEmpPanel.setVisible(true);
                empEditedLabel.setVisible(false);
                empNum.setText(String.valueOf(empEdited.getEmpNum()));
                firstName.setText(empEdited.getFirstName());
                lastName.setText(empEdited.getLastName());
                deductRate.setText(String.valueOf(empEdited.getEmpDeductRate()*100));

                //Set gender
                if (empEdited.getEmpGender() == 0) {
                    otherGender.setSelected(true);
                }

                if (empEdited.getEmpGender() == 1) {
                    male.setSelected(true);
                }

                if (empEdited.getEmpGender() == 2) {
                    female.setSelected(true);
                }

                //Set workLoc
                if (empEdited.getEmpWorkLoc() == 0) {
                    workLocMississauga.setSelected(true);
                }

                if (empEdited.getEmpWorkLoc() == 1) {
                    workLocBrampton.setSelected(true);
                }

                if (empEdited.getEmpWorkLoc() == 2) {
                    workLocOakville.setSelected(true);
                }
                
                
                //SetEmpType
                if (empEdited instanceof PTE) {
                    PTE.setSelected(true);
                }

                if (empEdited instanceof FTE) {
                    FTE.setSelected(true);
                }
                
                //Set sub class info
                if (empEdited instanceof FTE) {
                    empEditedFTE = (FTE) empEdited;
                    yearSalary.setText(Double.toString(empEditedFTE.getYearlySalary()));
                    FTEPanel.setVisible(true);
                    PTEPanel.setVisible(false);
                    
                    //Resets PTE panel
                    hourWage.setText("");
                    hourPerWeek.setText("");
                    weekPerYear.setText("");
                }
                
                if (empEdited instanceof PTE) {
                    empEditedPTE = (PTE) empEdited;
                    hourWage.setText(Double.toString(empEditedPTE.getHourWage()));
                    hourPerWeek.setText(Double.toString(empEditedPTE.getHourPerWeek()));
                    weekPerYear.setText(Double.toString(empEditedPTE.getWeekPerYear()));
                    PTEPanel.setVisible(true);
                    FTEPanel.setVisible(false);
                    
                    //Resets FTE panel
                    yearSalary.setText("");
                }
                
            } else {
                System.out.println("Employee cannot be found");
                errorLabel.setVisible(true);
                editEmpPanel.setVisible(false);

            }
        }
    }//GEN-LAST:event_findEmpActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        //Closes AddEmployee tab
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //Save HashTable to archive file after close
        mainHT.saveToFile("D:\\Dump\\CompSci\\HTarchive.txt");
    }//GEN-LAST:event_formWindowClosing

    private void otherGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherGenderActionPerformed
        // TODO add your handling code here:
        //Sets gender to other, which is 0
        empGender = 0;
    }//GEN-LAST:event_otherGenderActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        //Sets gender to male, which is 1
        empGender = 1;
    }//GEN-LAST:event_maleActionPerformed

    private void disposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disposeActionPerformed
        // TODO add your handling code here:
        //Closes AddEmployee Tab
        editEmpPanel.setVisible(false);
    }//GEN-LAST:event_disposeActionPerformed

    private void workLocMississaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocMississaugaActionPerformed
        // TODO add your handling code here:
        //Sets work location to Mississauga, which is 1
        workLoc = 1;
    }//GEN-LAST:event_workLocMississaugaActionPerformed

    private void workLocBramptonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocBramptonActionPerformed
        // TODO add your handling code here:
        //Sets work location to Brampton, which is 2
        workLoc = 2;
    }//GEN-LAST:event_workLocBramptonActionPerformed

    private void workLocOakvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocOakvilleActionPerformed
        // TODO add your handling code here:
        //Sets work location to Oakville, which is 3
        workLoc = 3;
    }//GEN-LAST:event_workLocOakvilleActionPerformed

    private void FTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTEActionPerformed
        // TODO add your handling code here:
        //Sets FTE panel visible
        PTEPanel.setVisible(false);
        FTEPanel.setVisible(true);
        empType = 0;
    }//GEN-LAST:event_FTEActionPerformed

    private void PTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTEActionPerformed
        // TODO add your handling code here:
        //Sets PTE panel visible
        PTEPanel.setVisible(true);
        FTEPanel.setVisible(false);
        empType = 1;
    }//GEN-LAST:event_PTEActionPerformed

    private void addToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToTableActionPerformed
        // TODO add your handling code here:
        //Edits employee keeping the refval-adds new refval if subclass is changed

        if ("".equals(empNum.getText()) || "".equals(firstName.getText()) || "".equals(lastName.getText()) || "".equals(deductRate.getText())) { //Detects for empty text fields
            System.out.println("empty fields");
            error.setVisible(true);
        } else {
            //Input for employee number of added employee
            String employeeNumString = empNum.getText();
            int employeeNum = Integer.parseInt(employeeNumString);
            EmployeeInfo isInTable = mainHT.searchFromTable(employeeNum);
            
            if(empEdited.getEmpNum() == employeeNum){//Keeping the same emp num wont be detected as duplicate
                isInTable = null;
            }

            //Input for first and last names
            String employeeFirst = firstName.getText();
            String employeeLast = lastName.getText();

            //Input for deduction rate
            String employeeDeductString = deductRate.getText();
            double employeeDeduct = Double.parseDouble(employeeDeductString) / 100;

            if (empType == 0) {//Adds FTE 

                if ("".equals(yearSalary.getText()) || isInTable != null) {//Detects FTE empty fields and detects duplicate emp#
                    System.out.println("empty fields or emp# already exists");
                    error.setVisible(true);
                } else {
                    
                    error.setVisible(false);
                    String employeeYearSalaryString = yearSalary.getText();
                    double employeeYearSalary = Double.parseDouble(employeeYearSalaryString);

                    if (empEdited instanceof FTE) {//Edits existing reference value

                        empEditedFTE = (FTE) empEdited;

                        empEditedFTE.modify(employeeNum, employeeFirst, employeeLast, empGender, workLoc, employeeDeduct);
                        empEditedFTE.modifyFTE(employeeYearSalary);
                        System.out.println("Edited the FTE to the hash table!");
                        empEditedLabel.setVisible(true);
                        error.setVisible(false);

                    } else {//Creates new reference value and deletes old one
                        mainHT.removeFromTable(empEdited.getEmpNum());
                        empEditedFTE = new FTE(employeeNum, employeeFirst, employeeLast, empGender, workLoc, employeeDeduct, employeeYearSalary);
                        mainHT.addToTable(empEditedFTE);
                        empEdited = empEditedFTE;
                        System.out.println("Edited the FTE to the hash table!(new refVal)");
                        empEditedLabel.setVisible(true);
                        error.setVisible(false);
                    }
                }
            }

            if (empType == 1) {//Adds PTE 

                if ("".equals(hourWage.getText()) || "".equals(hourPerWeek.getText()) || "".equals(weekPerYear.getText()) || isInTable != null) {//Detects PTE empty fields and detects duplicate emp#
                    System.out.println("empty fields or emp# already exists");
                    error.setVisible(true);
                } else {
                    
                    error.setVisible(false);
                    String employeeHourWageString = hourWage.getText();
                    double employeeHourWage = Double.parseDouble(employeeHourWageString);

                    String employeeHourPerWeekString = hourPerWeek.getText();
                    double employeeHourPerWeek = Double.parseDouble(employeeHourPerWeekString);

                    String employeeWeekPerYearString = weekPerYear.getText();
                    double employeeWeekPerYear = Double.parseDouble(employeeWeekPerYearString);

                    if (empEdited instanceof PTE) {

                        empEditedPTE = (PTE) empEdited;

                        empEditedPTE.modify(employeeNum, employeeFirst, employeeLast, empGender, workLoc, employeeDeduct);
                        empEditedPTE.modifyPTE(employeeHourWage, employeeHourPerWeek, employeeWeekPerYear);
                        System.out.println(" Edited the PTE to the hash table!");
                        empEditedLabel.setVisible(true);
                        error.setVisible(false);
                    } else {

                        mainHT.removeFromTable(empEdited.getEmpNum());
                        empEditedPTE = new PTE(employeeNum, employeeFirst, employeeLast, empGender, workLoc, employeeDeduct, employeeHourWage, employeeHourPerWeek, employeeWeekPerYear);
                        mainHT.addToTable(empEditedPTE);
                        empEdited = empEditedPTE;
                        System.out.println("Edited the PTE to the hash table!(new refVal)");
                        empEditedLabel.setVisible(true);
                        error.setVisible(false);
                    }
                }
            }
        }
    }//GEN-LAST:event_addToTableActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        //Sets gender to female, which is 2
        empGender = 2;
    }//GEN-LAST:event_femaleActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FTE;
    private javax.swing.JPanel FTEPanel;
    private javax.swing.JRadioButton PTE;
    private javax.swing.JPanel PTEPanel;
    private javax.swing.JButton addToTable;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField deductRate;
    private java.awt.Label deductRateLabel;
    private javax.swing.JButton dispose;
    private javax.swing.JPanel editEmpPanel;
    private javax.swing.JLabel empEditedLabel;
    private javax.swing.JTextField empFind;
    private javax.swing.JTextField empNum;
    private javax.swing.JLabel empNumLabel;
    private java.awt.Label empNumLabel1;
    private javax.swing.ButtonGroup empTypeButtonGroup;
    private java.awt.Label empTypeLabel;
    private javax.swing.JLabel error;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton findEmp;
    private javax.swing.JTextField firstName;
    private java.awt.Label firstNameLabel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private java.awt.Label genderLabel;
    private javax.swing.JTextField hourPerWeek;
    private java.awt.Label hourPerWeekLabel;
    private javax.swing.JTextField hourWage;
    private java.awt.Label hourWageLabel;
    private javax.swing.JTextField lastName;
    private java.awt.Label lastNameLabel;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel nullLabel;
    private javax.swing.JRadioButton otherGender;
    private java.awt.Label percentLabel;
    private javax.swing.JTextField weekPerYear;
    private java.awt.Label weekPerYearLabel;
    private javax.swing.JRadioButton workLocBrampton;
    private javax.swing.ButtonGroup workLocButtonGroup;
    private java.awt.Label workLocLabel;
    private javax.swing.JRadioButton workLocMississauga;
    private javax.swing.JRadioButton workLocOakville;
    private javax.swing.JTextField yearSalary;
    private java.awt.Label yearSalaryLabel;
    // End of variables declaration//GEN-END:variables
}
