/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dingr
 */
public class RemoveEmployee extends javax.swing.JFrame {

    // ATTRIBUTES
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.
    private EmployeeInfo empRemoved; 
    
    // METHODS
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
    
    //CONSTRUCTORS
    /**
     * Creates new form RemoveEmployee
     */
    public RemoveEmployee() {
        initComponents();
        
        //Error labels
        empErrorLabel.setVisible(false);
        empNullLabel.setVisible(false);
        successLabel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empRemove = new javax.swing.JTextField();
        removeEmp = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        undoEmp = new javax.swing.JButton();
        empNumLabel = new javax.swing.JLabel();
        empErrorLabel = new javax.swing.JLabel();
        empNullLabel = new javax.swing.JLabel();
        successLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        removeEmp.setText("Remove");
        removeEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmpActionPerformed(evt);
            }
        });

        cancel.setText("Exit");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        undoEmp.setText("Undo");
        undoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoEmpActionPerformed(evt);
            }
        });

        empNumLabel.setText("Employee Number:");

        empErrorLabel.setText("Error: Could not find employee");

        empNullLabel.setText("Please add an employee number.");

        successLabel.setText("Item successfully removed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNumLabel)
                            .addComponent(empRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(removeEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(empErrorLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(undoEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(empNullLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(successLabel)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(empErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNullLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(successLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeEmp)
                    .addComponent(cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undoEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmpActionPerformed
        // TODO add your handling code here:
        //Remove employee mentioned in the emp number
        if (empRemove.getText().equals("")) {//No number input
            System.out.println("No employee number added");
            empNullLabel.setVisible(true);
            empErrorLabel.setVisible(false);
            successLabel.setVisible(false);
        } else {
            
            empNullLabel.setVisible(false);
            empErrorLabel.setVisible(false);

            int empRemoveInt = Integer.parseInt(empRemove.getText());
            empRemoved = mainHT.removeFromTable(empRemoveInt);
            successLabel.setVisible(true);

            if (empRemoved == null) {
                System.out.println("Employee cannot be found");
                empErrorLabel.setVisible(true);
                successLabel.setVisible(false);
            } else {
                System.out.println("Employee successfully removed");
            }
        }
    }//GEN-LAST:event_removeEmpActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        //Closes AddEmployee Tab
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //Save HashTable to archive file after close
        mainHT.saveToFile("D:\\Dump\\CompSci\\HTarchive.txt");
    }//GEN-LAST:event_formWindowClosing

    private void undoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoEmpActionPerformed
        // TODO add your handling code here:
        //Adds recently deleted employee back to HT
        if(empRemoved != null){
            mainHT.addToTable(empRemoved);
            empRemoved = null;
            System.out.println("Employee Re-added");
        } else {
            System.out.println("Employee unable to be Re-added :(");
        }
    }//GEN-LAST:event_undoEmpActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveEmployee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel empErrorLabel;
    private javax.swing.JLabel empNullLabel;
    private javax.swing.JLabel empNumLabel;
    private javax.swing.JTextField empRemove;
    private javax.swing.JButton removeEmp;
    private javax.swing.JLabel successLabel;
    private javax.swing.JButton undoEmp;
    // End of variables declaration//GEN-END:variables
}
